name: ndt
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=2.128=openblas
  - blas-devel=3.9.0=28_h1ea3ea9_openblas
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2025.1.31=py39h06a4308_0
  - contourpy=1.2.1=py39hdb19cb5_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.4=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py39h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libblas=3.9.0=28_h59b9bed_openblas
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcblas=3.9.0=28_he106b2a_openblas
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.11.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=28_h7ac8fdf_openblas
  - liblapacke=3.9.0=28_he2f377e_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - llvm-openmp=19.1.7=h024ca30_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.9.2=py39h06a4308_1
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - mkl=2024.2.2=ha957f24_16
  - mkl-service=2.4.2=py39h0296b93_0
  - mkl_fft=1.3.11=py39h3f936ba_0
  - mkl_random=1.2.8=py39h7a87aa2_1
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - networkx=3.2.1=py39h06a4308_0
  - numexpr=2.10.1=py39hd28fd6d_0
  - numpy=1.26.4=py39heeff2f4_0
  - numpy-base=1.26.4=py39h8a23956_0
  - openblas=0.3.28=pthreads_h6ec200e_1
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.4.0=h7b32b05_1
  - packaging=24.2=py39h06a4308_0
  - pandas=2.2.3=py39h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py39hcea889d_0
  - pip=25.0=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - pybind11-abi=4=hd3eb1b0_1
  - pyparsing=3.2.0=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_1
  - pyqt5-sip=12.13.0=py39h5eee18b_1
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - qt-main=5.15.2=hb6262e9_11
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.6.1=py39h6a678d5_0
  - scikit-multiflow=0.5.3=py39h78703db_2
  - scipy=1.13.1=py39heeff2f4_1
  - setuptools=75.8.0=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_1
  - six=1.16.0=pyhd3eb1b0_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.4.2=py39h5eee18b_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_1
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.5.0
      - charset-normalizer==3.4.1
      - flatbuffers==24.12.23
      - gast==0.6.0
      - google-auth==2.37.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.12.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - keras==2.14.0
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==3.0.2
      - mininet==2.3.0.dev6
      - ml-dtypes==0.2.0
      - oauthlib==3.2.2
      - opt-einsum==3.4.0
      - protobuf==4.25.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pytz==2025.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - river==0.21.2
      - rsa==4.9
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wrapt==1.14.1
prefix: /home/claudio/miniconda3/envs/ndt
